spring.profiles.active: development
---
spring:
  profiles: cloud
  neo4j:
    host: ${SPRING_NEO4J_HOST:192.168.10.152}
    port: ${SPRING_NEO4J_PORT:7474}
    username: neo4j
    password: 123
---
spring:
  profiles: development
  neo4j:
    host: ${SPRING_NEO4J_HOST:192.168.10.152}
    port: ${SPRING_NEO4J_PORT:7474}
    username: neo4j
    password: 123
---
spring:
  profiles: docker
  neo4j:
    host: ${SPRING_NEO4J_HOST:neo4j}
    port: ${SPRING_NEO4J_PORT:7474}
    username: neo4j
    password: 123
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
---
spring:
  profiles: test
  neo4j:
    host: ${SPRING_NEO4J_HOST:192.168.10.152}
    port: ${SPRING_NEO4J_PORT:7474}
    username: neo4j
    password: 123
eureka:
  client:
    enabled: false
